### ISSUE TITLE
Tests something panic

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#280]
https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-github/785/workflows/031b075a-a760-41a2-aa6b-0deff45087aa:

```bash
/usr/local/go/bin/go test -race -coverprofile=server/coverage.txt ./server/...
--- FAIL: TestPlugin_ServeHTTP (0.00s)
    --- FAIL: TestPlugin_ServeHTTP/unauthorized_test_json (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x300 pc=0xfc8e26]

goroutine 32 [running]:
testing.tRunner.func1.1(0x10fdc00, 0x1a7fa50)
	/usr/local/go/src/testing/testing.go:941 +0x5d0
testing.tRunner.func1(0xc0001d9e60)
	/usr/local/go/src/testing/testing.go:944 +0x600
panic(0x10fdc00, 0x1a7fa50)
	/usr/local/go/src/runtime/panic.go:973 +0x3e3
github.com/mattermost/mattermost-plugin-github/server.(*Plugin).getGitHubUserInfo(0xc0002feaf0, 0x1218be8, 0x0, 0x1218be8, 0x0)
	/home/circleci/project/server/plugin.go:248 +0xf6
github.com/mattermost/mattermost-plugin-github/server.(*Plugin).getConnected(0xc0002feaf0, 0x13b87e0, 0xc0002fc900, 0xc00020b700)
	/home/circleci/project/server/api.go:356 +0x25c
net/http.HandlerFunc.ServeHTTP(0xc0002e59f0, 0x13b87e0, 0xc0002fc900, 0xc00020b700)
	/usr/local/go/src/net/http/server.go:2012 +0x52
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000400000, 0x13b87e0, 0xc0002fc900, 0xc00020b600)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0x13f
github.com/mattermost/mattermost-plugin-github/server.(*Plugin).ServeHTTP(0xc0002feaf0, 0x0, 0x13b87e0, 0xc0002fc900, 0xc00020b500)
	/home/circleci/project/server/api.go:118 +0x1ca
github.com/mattermost/mattermost-plugin-github/server.TestPlugin_ServeHTTP.func1(0xc0001d9e60)
	/home/circleci/project/server/api_test.go:79 +0x5f5
testing.tRunner(0xc0001d9e60, 0xc0002e5740)
	/usr/local/go/src/testing/testing.go:992 +0x1ec
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x661
FAIL	github.com/mattermost/mattermost-plugin-github/server	0.045s
?   	github.com/mattermost/mattermost-plugin-github/server/testutils	[no test files]
FAIL
make: *** [Makefile:129: coverage] Error 1
```

**Comment by hanzei** [comment]
Actually, the test failure only happens in `278_public-connected`. No issues on `master`.
